"""initial schema

Revision ID: f13d3553e8f5
Revises: 
Create Date: 2026-09-19 21:17:12.619712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f13d3553e8f5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_holidays',
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('attendance_staff',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('department', sa.String(length=80), nullable=True),
    sa.Column('designation', sa.String(length=120), nullable=True),
    sa.Column('monthly_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payroll_monthly',
    sa.Column('month', sa.String(length=20), nullable=False),
    sa.Column('advance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('final', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('month')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=190), nullable=False),
    sa.Column('personal_email', sa.String(length=190), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('admin', 'staff', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('active', 'disabled', name='userstatus'), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('designation', sa.String(length=120), nullable=True),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('employee_id', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('aadhaar', sa.String(length=20), nullable=True),
    sa.Column('current_address', sa.String(length=255), nullable=True),
    sa.Column('permanent_address', sa.String(length=255), nullable=True),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('can_manage_access', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.String(length=20), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('present', 'wfh', 'absent', 'late', 'half_day', name='attendancestatus'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['attendance_staff.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_id', 'date')
    )
    op.create_table('company_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sr_no', sa.String(length=20), nullable=True),
    sa.Column('invoice_no', sa.String(length=50), nullable=True),
    sa.Column('lrn', sa.String(length=50), nullable=True),
    sa.Column('vehicle', sa.String(length=30), nullable=True),
    sa.Column('mt', sa.String(length=20), nullable=True),
    sa.Column('trader_name', sa.String(length=150), nullable=True),
    sa.Column('destination_city', sa.String(length=120), nullable=True),
    sa.Column('do_number', sa.String(length=150), nullable=True),
    sa.Column('freight', sa.String(length=30), nullable=True),
    sa.Column('amount', sa.String(length=30), nullable=True),
    sa.Column('gst_18', sa.String(length=30), nullable=True),
    sa.Column('total_amount', sa.String(length=30), nullable=True),
    sa.Column('submit_status', sa.String(length=60), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('date', sa.String(length=30), nullable=True),
    sa.Column('expense', sa.String(length=30), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('freight_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destination', sa.String(length=120), nullable=False),
    sa.Column('rate', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('destination')
    )
    op.create_table('gps_records',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('gps_id', sa.String(length=60), nullable=True),
    sa.Column('date_issued', sa.String(length=30), nullable=True),
    sa.Column('vehicle_number', sa.String(length=30), nullable=True),
    sa.Column('gps_type', sa.String(length=60), nullable=True),
    sa.Column('gps_amount', sa.String(length=30), nullable=True),
    sa.Column('gps_return', sa.String(length=30), nullable=True),
    sa.Column('return_date', sa.String(length=30), nullable=True),
    sa.Column('amount_return', sa.String(length=30), nullable=True),
    sa.Column('late_fee', sa.String(length=30), nullable=True),
    sa.Column('balance_due', sa.String(length=30), nullable=True),
    sa.Column('owner', sa.String(length=120), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sr_no', sa.String(length=20), nullable=True),
    sa.Column('invoice_no', sa.String(length=50), nullable=True),
    sa.Column('invoice_date', sa.String(length=30), nullable=True),
    sa.Column('loading_date', sa.String(length=30), nullable=True),
    sa.Column('unloading_date', sa.String(length=30), nullable=True),
    sa.Column('lrn', sa.String(length=50), nullable=True),
    sa.Column('vehicle', sa.String(length=30), nullable=True),
    sa.Column('mt', sa.String(length=20), nullable=True),
    sa.Column('trader_name', sa.String(length=150), nullable=True),
    sa.Column('destination_city', sa.String(length=120), nullable=True),
    sa.Column('do_number', sa.String(length=150), nullable=True),
    sa.Column('pahuch_status', sa.String(length=60), nullable=True),
    sa.Column('invoice_status', sa.String(length=60), nullable=True),
    sa.Column('pahuch_upload_status', sa.String(length=60), nullable=True),
    sa.Column('invoice_upload_status', sa.String(length=60), nullable=True),
    sa.Column('vehicle_type', sa.String(length=60), nullable=True),
    sa.Column('company_freight', sa.String(length=30), nullable=True),
    sa.Column('company_total_amount', sa.String(length=30), nullable=True),
    sa.Column('gst_18', sa.String(length=30), nullable=True),
    sa.Column('bill_amount', sa.String(length=30), nullable=True),
    sa.Column('received_amount', sa.String(length=30), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sr_no', sa.String(length=20), nullable=True),
    sa.Column('payment_voucher_status', sa.String(length=60), nullable=True),
    sa.Column('loading_date', sa.String(length=30), nullable=True),
    sa.Column('unloading_date', sa.String(length=30), nullable=True),
    sa.Column('lrn', sa.String(length=50), nullable=True),
    sa.Column('vehicle', sa.String(length=30), nullable=True),
    sa.Column('mt', sa.String(length=20), nullable=True),
    sa.Column('trader_name', sa.String(length=150), nullable=True),
    sa.Column('destination_city', sa.String(length=120), nullable=True),
    sa.Column('freight', sa.String(length=30), nullable=True),
    sa.Column('total_amount', sa.String(length=30), nullable=True),
    sa.Column('do_number', sa.String(length=150), nullable=True),
    sa.Column('payment_status', sa.String(length=60), nullable=True),
    sa.Column('payment_mode_advance', sa.String(length=60), nullable=True),
    sa.Column('payment_advance_amt', sa.String(length=30), nullable=True),
    sa.Column('payment_date_advance', sa.String(length=30), nullable=True),
    sa.Column('payment_mode_final', sa.String(length=60), nullable=True),
    sa.Column('payment_final_amt', sa.String(length=30), nullable=True),
    sa.Column('payment_date_final', sa.String(length=30), nullable=True),
    sa.Column('payment_image_link_advance', sa.String(length=500), nullable=True),
    sa.Column('payment_image_link_final', sa.String(length=500), nullable=True),
    sa.Column('company_charges', sa.String(length=30), nullable=True),
    sa.Column('gps_charges', sa.String(length=30), nullable=True),
    sa.Column('party_difference', sa.String(length=30), nullable=True),
    sa.Column('difference_amount', sa.String(length=30), nullable=True),
    sa.Column('company_freight', sa.String(length=30), nullable=True),
    sa.Column('company_total_amount', sa.String(length=30), nullable=True),
    sa.Column('gst_18', sa.String(length=30), nullable=True),
    sa.Column('bill_amount', sa.String(length=30), nullable=True),
    sa.Column('received_amount', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('received_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sr_no', sa.String(length=20), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=True),
    sa.Column('loading_date', sa.String(length=30), nullable=True),
    sa.Column('vehicle_number', sa.String(length=30), nullable=True),
    sa.Column('lrn', sa.String(length=50), nullable=True),
    sa.Column('mt', sa.String(length=20), nullable=True),
    sa.Column('trader_name', sa.String(length=150), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('do_number', sa.String(length=150), nullable=True),
    sa.Column('invoice_amount', sa.String(length=30), nullable=True),
    sa.Column('received_amount', sa.String(length=30), nullable=True),
    sa.Column('received_date', sa.String(length=30), nullable=True),
    sa.Column('remaining_amount', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registration_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('login_email', sa.String(length=190), nullable=False),
    sa.Column('personal_email', sa.String(length=190), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('aadhaar', sa.String(length=20), nullable=True),
    sa.Column('designation', sa.String(length=120), nullable=True),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('employee_id', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('current_address', sa.String(length=255), nullable=True),
    sa.Column('permanent_address', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='registrationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decided_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sr_no', sa.String(length=20), nullable=True),
    sa.Column('trader_name', sa.String(length=150), nullable=True),
    sa.Column('contact_person', sa.String(length=120), nullable=True),
    sa.Column('mobile_number', sa.String(length=20), nullable=True),
    sa.Column('alternate_mobile', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=190), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('gst_number', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_module_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.String(length=30), nullable=False),
    sa.Column('section_id', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'module_id', 'section_id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sr_no', sa.String(length=20), nullable=True),
    sa.Column('vehicle_number', sa.String(length=30), nullable=True),
    sa.Column('truck_type', sa.String(length=60), nullable=True),
    sa.Column('owner_name', sa.String(length=120), nullable=True),
    sa.Column('owner_mobile', sa.String(length=20), nullable=True),
    sa.Column('alternate_mobile', sa.String(length=20), nullable=True),
    sa.Column('driver_name', sa.String(length=120), nullable=True),
    sa.Column('driver_mobile', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('rc_number', sa.String(length=30), nullable=True),
    sa.Column('pan_number', sa.String(length=20), nullable=True),
    sa.Column('aadhaar_number', sa.String(length=20), nullable=True),
    sa.Column('rc_image_path', sa.String(length=255), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicles')
    op.drop_table('user_module_access')
    op.drop_table('traders')
    op.drop_table('registration_requests')
    op.drop_table('received_payments')
    op.drop_table('payments')
    op.drop_table('invoices')
    op.drop_table('gps_records')
    op.drop_table('freight_rates')
    op.drop_table('expenses')
    op.drop_table('company_payments')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('payroll_monthly')
    op.drop_table('attendance_staff')
    op.drop_table('attendance_holidays')
    # ### end Alembic commands ###
